/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package docz;

import com.sun.media.sound.EmergencySoundbank;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michael
 */
public class FullScreenPreview extends javax.swing.JDialog {
    
    private Entity entity;
    private int currentIndex = 0;
    private String[] fileNames;
    private Dimension screenSize;
    /**
     * Creates new form FullScreenPreview
     */
    public FullScreenPreview(java.awt.Frame parent, Entity entity, String initialSelection) throws Exception {
        super(parent, true);
        initComponents();
        this.entity = entity;
        this.fileNames = DataHandler.instance.getFileNames(entity);
        for(int i=0; i<fileNames.length; i++){
            if(initialSelection.equals(fileNames[i])){
                currentIndex = i;
            }
        }
        
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        
        imgPreview.setImg(DataHandler.instance.getThumbnail(entity, fileNames[currentIndex], screenSize.width, screenSize.height, new Font("Arial", Font.BOLD, 30)));
        imgPreview.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        imgPreview = new docz.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview");

        btnNext.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imgPreviewLayout = new javax.swing.GroupLayout(imgPreview);
        imgPreview.setLayout(imgPreviewLayout);
        imgPreviewLayout.setHorizontalGroup(
            imgPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imgPreviewLayout.setVerticalGroup(
            imgPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            currentIndex++;
            currentIndex = currentIndex % fileNames.length;
            imgPreview.setImg(DataHandler.instance.getThumbnail(entity, fileNames[currentIndex], screenSize.width, screenSize.height, new Font("Arial", Font.BOLD, 30)));
        } catch (Exception ex) {
            Log.l(ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        try {
            currentIndex = currentIndex - 1 < 0 ? fileNames.length - 1 : currentIndex - 1;
            currentIndex = currentIndex % fileNames.length;
            imgPreview.setImg(DataHandler.instance.getThumbnail(entity, fileNames[currentIndex], screenSize.width, screenSize.height, new Font("Arial", Font.BOLD, 30)));
        } catch (Exception ex) {
            Log.l(ex);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private docz.ImagePanel imgPreview;
    // End of variables declaration//GEN-END:variables
}
